# **Python - NumPy Tutorial**

#### Reference: [https://www.tutorialspoint.com/numpy/index.htm](https://www.tutorialspoint.com/numpy/index.htm)

In [3]:
import numpy as np

## **NumPy - Indexing & Slicing**

### One Dimensional Array Slicing

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
s1 = slice(1,9,2) # slice(start,stop,step)

In [7]:
arr[s1]

array([1, 3, 5, 7])

In [8]:
arr[1:9:2]

array([1, 3, 5, 7])

##### Slice Items Starting from an Index 

In [9]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

##### Slice Items Between Indexes

In [10]:
arr[5:8]

array([5, 6, 7])

### N Dimensional Array Slicing

In [11]:
arr2x5 = arr.reshape(2,5)

In [12]:
arr2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
arr2x5[...,1:3]

array([[1, 2],
       [6, 7]])

In [14]:
arr2x5[:,3]

array([3, 8])

In [15]:
arr2x5[1,:]

array([5, 6, 7, 8, 9])

In [16]:
arr3x3=np.array([[1,2,3],[3,4,5],[4,5,6]]) 

In [17]:
arr3x3

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [18]:
arr3x3[1:,]

array([[3, 4, 5],
       [4, 5, 6]])

In [19]:
arr3x3[:1,:]

array([[1, 2, 3]])

In [20]:
arr3x3[:1,...]

array([[1, 2, 3]])

In [21]:
arr3x3[:2,1:]

array([[2, 3],
       [4, 5]])

In [22]:
arr3x3[1:,1:]

array([[4, 5],
       [5, 6]])

## **NumPy - Advanced Indexing**

## Integer Indexing

This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index. Each integer array represents the number of indexes into that dimension. When the index consists of as many integer arrays as the dimensions of the target ndarray, it becomes straightforward.

In the following example, one element of specified column from each row of ndarray object is selected. Hence, the row index contains all row numbers, and the column index specifies the element to be selected.

In [23]:
x1 = np.array([[1, 2], [3, 4], [5, 6]])

In [24]:
x1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
rows_1 = [0,1,2]
cols_1 = [0,1,0]

In [26]:
y1 = x1[rows_1,cols_1]

In [27]:
y1

array([1, 4, 5])

In [28]:
x2 = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

In [29]:
x2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
rows_2 = np.array([[0,0],[3,3]])
cols_2 = np.array([[0,2],[0,2]]) 

In [31]:
rows_2

array([[0, 0],
       [3, 3]])

In [32]:
cols_2

array([[0, 2],
       [0, 2]])

In [34]:
y2 = x2[rows_2,cols_2]

In [35]:
y2

array([[ 0,  2],
       [ 9, 11]])

#### Combine Advanced and Basic Indexing with Slice (:) or Ellipsis (...)

Advanced and basic indexing can be combined by using one slice (:) or ellipsis (…) with an index array. The following example uses slice for row and advanced index for column. The result is the same when slice is used for both. But advanced index results in copy and may have different memory layout.

In [41]:
x3 = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

In [42]:
x3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
x3[1:4,1:3]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [44]:
x3[1:4,[1,2]]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

## Boolean Array Indexing

In [69]:
v1 = np.arange(12).reshape(4,3)

In [85]:
v1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
v1[v1<=8]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
v2 = np.array([np.nan, 1,2,np.nan,3,4,5]) 

In [67]:
v2[np.isnan(v2)]

array([nan, nan])

In [71]:
v2[~np.isnan(v2)]

array([1., 2., 3., 4., 5.])

In [79]:
v3 = np.array([1, 2+6j, 5, 3.5+5j]) 

In [75]:
v3[np.iscomplex(v3)]

array([2. +6.j, 3.5+5.j])

In [77]:
np.iscomplex(v3)

array([False,  True, False,  True])